### ISSUE TITLE
Issue with chunk ID creation when delete a partition and reingest data

### ISSUE THREAD

**Issue by parekuti** [filodb/FiloDB#115]

**Comment by parekuti** [comment]
Evan, as discussed we have a requirement to perform row level deletes. So created a small utility using spark scala for this. Our delete strategy is.. 
For each partition 
- Load dataset into dataframe and filter DF for non-delete rows
- Delete partition from chunkrowmap, chunk table using CQL
- Reingest data for the same partition using filodb.spark

When we do this operation in a loop, for example partition A has 2000 rows and partition B has 5400 rows. 2 chunk IDs are created for partition A even though our chunk size is set as 5000 during the ingestion.

**Comment by velvia** [comment]
@parekuti thanks.  As discussed, this is most likely due not necessarily to the delete itself, but the fact that

1) The segment cache in the ColumnStore has gotten out of sync with the deletion, and
2) repeated read-delete-write cycles cause different partition keys to show up in different nodes, since Spark and current implementation does not place partitions in particular node.

Both of these issues can be resolved if we 

a) provide a way for column store segment cache to be cleared programmatically (we need to provide an API in the Coordinator Client. This sends a message to each NodeCoordinatorActor, which would need to call the clearCache method in the column store.   I would call this method clearIngestionCache.

b) optionally provide an option in the Spark DataFrame writer to call this before the start of ingestion.  That is one way to make the streaming consistent before we implement sorting.

Long term though the solution is proper sorting, which I'm working on.   So maybe implement a) and not b)?

**Comment by velvia** [comment]
@parekuti can I close this for now?  The code base has changed a lot since this was filed and we now have sorting/routing on ingest automatically, so the issue should be gone.   Please test on the new segment less code base on master/spark1.6 and feel free to reopen if the issue still persists.
