### ISSUE TITLE
Provide functionality to delete specific row on FiloDB table

### ISSUE THREAD

**Issue by parekuti** [filodb/FiloDB#88]

**Comment by velvia** [comment]
So there are lots to think about here.

## API for deleting rows

Spark doesn't provide an API for deleting any data at all.  It cannot be represented through the standard DataFrame write API.

The CLI could have some command to delete a set of rows.  The data would have to be provided, perhaps by passing in a CSV file with only the partition, segment, and row keys (e.g. the primary keys) of data to be deleted.

A similar concept could in theory be applied in Spark.  Start with a DataFrame containing only the primary key columns, and maybe invoke a special API, like `FiloContext.deleteRows()`.

## How to Represent Deleted Rows

- In the MemTable, we would need to add a list of primary keys to delete.  There are two cases: when that key is in the memtable already (in which case, don't write it out), or when it isn't.
- On disk, there are two possibilities.
    - The deleted rows could be represented by a new special bitmap column, representing rows to be deleted.  Think of it as like a new hidden DELETED flag column, or one extra flag per record.    This would need to be read with every read and handled at read time.
    - The ChunkRowMapIndex could simply be updated such that deleted rows would be removed from the index.  This would result in no performance degradation at read time.

The problem with all of this is that the disk format will change.  If we went with the latter option this would then need to be reimplemented.

There are changes needed through the entire ingestion stack as well as some on the read path.
- Deletes would need to come in through the NodeCoordinator / DatasetCoordinator / MemTable / Reprojector ingestion stack, because it could affect the data in the memtable which hasn't flushed yet, and because it affects the data being written.
- One could delete rows at any point in time
- 

How about proposing or commenting on the ideas above?
